# .gnupg/gpg-agent.conf
# @author nate zhou
# @since 2025,2026

# password cache lifetime in second (align with reference: 28 days)
default-cache-ttl 2419200
max-cache-ttl 2419200
pinentry-program /usr/bin/pinentry-tty
# required for PassCmd: gpg --decrypt --pinentry-mode loopback
allow-loopback-pinentry
