# vim:ft=lf
# local.conf
# @author nate zhou
# @since 2025

setlocal ~/Downloads dirfirst false
setlocal ~/tmp dirfirst false
setlocal ~/smb dirfirst false

setlocal ~/Documents/heart/ hidden!
setlocal ~/Documents/unixchad/ hidden!
setlocal ~/Documents/git/ hidden!
setlocal ~/Documents/git-private/ hidden!
setlocal ~/pkg/ollama/ hidden!
