[global]
   workgroup = WORKGROUP
   server string = %h server
   security = user
   map to guest = Bad User
   dns proxy = no

[homes]
   comment = Home Directories
   browseable = no
   writable = yes
   valid users = %S

[work]
   comment = work Shared Folder
   path = /home/pix/work
   browseable = yes
   writable = yes
   guest ok = no
   valid users = @sambashare
