# vim:ft=dosini
# foot/bindings.ini
# @author pix
# @since 2026

[key-bindings]
clipboard-copy=Control+Shift+c XF86Copy
#wl-paste
clipboard-paste=Control+Shift+v

color-theme-switch-dark=Control+Shift+minus
color-theme-switch-light=Control+Shift+equal

show-urls-copy=Control+Shift+y

[url-bindings]
toggle-url-visible=t

[mouse-bindings]
primary-paste=BTN_MIDDLE

[search-bindings]
# unbind default to avoid conflict
delete-to-end=none

find-prev=Control+p
find-next=Control+n
extend-char=Control+l
extend-backward-char=Control+h
extend-line-down=Control+j
extend-line-up=Control+k
extend-to-word-boundary=Control+w
commit=Return
