# vim:ft=dosini
# foot/colors-light.ini
# @author pix
# @since 2026

[colors-light]
# Novel 
alpha=1
background=dfdbc3  #dfdbc3
foreground=593534  #593534  
flash=7f7fee #7f7fee
flash-alpha=0.8

# 基础16色（Novel Light调色板）
# black
regular0=000000 #000000
# red
regular1=990000 #990000
# green
regular2=00a600 #00a600
# yellow
regular3=999900 #999900
# blue
regular4=0000b2 #0000b2
# magenta
regular5=b200b2 #b200b2
# cyan
regular6=00a6b2 #00a6b2
# white
regular7=bfbfbf #bfbfbf

# bright black
bright0=666666 #666666
# bright red
bright1=e50000 #e50000 
# bright green
bright2=00d900 #00d900 
# bright yellow
bright3=e5e500 #e5e500 
# bright blue
bright4=0000ff #0000ff
# bright magenta
bright5=e500e5 #e500e5
# bright cyan
bright6=00e5e5 #00e5e5 
# bright white
bright7=e5e5e5 #e5e5e5

# 选中文本颜色
selection-foreground=000000 #000000
# 选中背景色
selection-background=a4a390 #a4a390
# 滚动指示器
scrollback-indicator=242424 005577  #242424  #005577
