# vim:ft=dosini
# foot/bindings.ini
# @author pix
# @since 2026
include=~/.config/foot/bindings.ini
include=~/.config/foot/colors-dark.ini
include=~/.config/foot/colors-light.ini
term = xterm-256color
font=NotoSansM Nerd Font Mono:size=15,Noto Sans Mono CJK SC:size=15
[url]
launch=qutebrowser ${url}
# style=curly
style=double

[mouse]
hide-when-typing=yes
alternate-scroll-mode=yes

[bell]
visual=yes
