# .config/shell/teleport.conf
# @author nate zhou
# @since 2025,2026
# config file to generate keybindings for bash/zsh aliases
# and ranger/lf keybindings

,.="~/Documents/heart"
,h="~/Documents/heart"
,n="~/Documents/note"

,bi="/run/media/"
,br="$XDG_RUNTIME_DIR"


,D="~/Downloads"
,S="~/smb"
,T="~/tmp"
,V="~/virt"
,P="~/pkg"
,M="~/mnt"

,,s="~/.ssh"
,,g="~/.gnupg"

,gd="~/Documents/.gpg"
,gm="~/Music/.gpg"
,gp="~/Pictures/.gpg"
,gv="~/Videos/.gpg"

,rd="/data"

,,c="~/.config"
,cb="~/.config/bash"
,cc="~/.config/calcurse"
,cC="~/.config/Code\ -\ OSS/User"
,cd="~/.config/dunst"
,cf="~/.config/foot"
,cF="~/.config/firejail"
,cg="~/.config/git"
,ck="~/.config/kanshi"
,cl="~/.config/lf"
,cm="~/.config/mutt"
,cM="~/.config/mpd"
,cn="~/.config/newsboat"
,cN="~/.config/ncmpcpp"
,cv="~/.config/nvim"
,cq="~/.config/qutebrowser"
,cr="~/.config/river"
,cR="~/.config/river-classic"
,cs="~/.config/shell"
,ci="~/.config/swayimg"
,cI="~/.config/swayidle"
,cw="~/.config/wob"
,cy="~/.config/yt-dlp"
,cz="~/.config/zsh"
,cZ="~/.config/zathura"

,sa="~/.local/src/abduco"
,sv="~/.local/src/dvtm"
,sd="~/.local/src/dam"
,sl="~/.local/src/dwl"
,sb="~/.local/src/damblocks"
,sr="~/.local/src/river"
,sk="~/.local/src/kwm"
,si="~/.local/src/kwim"
,sc="~/.local/src/river-classic"
,sD="~/.local/src/riverdeck"
,ss="~/.local/src/river-shifttags"
,so="~/.local/src/rivercarro"
,sw="~/.local/src/dwm"
,st="~/.local/src/st"
,se="~/.local/src/dmenu"
,sn="~/.local/src/nsxiv"
,sz="~/.local/src/zoomx"
,sx="~/.local/src/x"

,,k="~/.cache"
,ky="~/.cache/yay"

,,l="~/.local"
,la="~/.local/app"
,lb="~/.local/bin"
,lB="~/.local/sbin"
,ls="~/.local/src"
,lA="~/.local/share/address"
,lp="~/.local/share/nvim/plugged"

,,d="~/Documents"
,db="~/Documents/books"
,dc="~/Documents/code"
,dd="~/Documents/dict"
,dG="~/Documents/gimp"
,dg="~/Documents/git"
,dh="~/Documents/httrack"
,dm="~/Documents/mail"
,dn="~/Documents/note"
,dp="~/Documents/private"
,du="~/Documents/unixchad"

,u.="~/Documents/unixchad/dotfiles"
,ug="~/Documents/unixchad/arch-install-guide"
,ua="~/Documents/unixchad/abduco"
,uv="~/Documents/unixchad/dvtm"
,ud="~/Documents/unixchad/dam"
,ul="~/Documents/unixchad/dwl"
,ub="~/Documents/unixchad/damblocks"
,um="~/Documents/unixchad/mew"
,uk="~/Documents/unixchad/kwm"
,ui="~/Documents/unixchad/kwim"
,ur="~/Documents/unixchad/river-classic"
,uD="~/Documents/unixchad/riverdeck"
,uw="~/Documents/unixchad/dwm"
,ut="~/Documents/unixchad/st"
,ue="~/Documents/unixchad/dmenu"
,un="~/Documents/unixchad/nsxiv"
,uz="~/Documents/unixchad/zoomx"
,ux="~/Documents/unixchad/x"
,uT="~/Documents/unixchad/toggle-term.nvim"
,uM="~/Documents/unixchad/mpv-stereoscopic"

,,m="~/Music"
,ma="~/Music/artists"
,mc="~/Music/classical"
,mC="~/Music/compilations"
,mm="~/Music/misc"
,mr="~/Music/recordings"
,ms="~/Music/soundtracks"

,,p="~/Pictures"
,pc="~/Pictures/camera"
,pC="~/Pictures/compilation"
,pk="~/Pictures/kirei"
,pm="~/Pictures/misc"
,ps="~/Pictures/Screenshots"
,pt="~/Pictures/templates"
,pu="~/Pictures/unixchad"
,pw="~/Pictures/wallpapers"

,,v="~/Videos"
,vc="~/Videos/camera"
,vk="~/Videos/kirei"
,vl="~/Videos/linux"
,vp="~/Videos/people"
,vP="~/Videos/personal"
,vu="~/Videos/unixchad"
,vt="~/Videos/unixchat"
