# git alias
alias grm="git rebase main"
alias grh="git rebase -i HEAD~~"
alias gd="git diff"
alias gdc="git diff --cached"
alias gdm="git diff main"
alias gp="git pull --rebase"
alias gpo="git push origin"
alias gpom="git push origin main"
alias gcm="git commit -m"
alias gm="git commit"
alias ga="git add"
alias gc="git checkout"
alias gcb="git checkout -b"
alias gco="git clone"
alias gs="git status"
alias gl="git log --graph --all --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(bold white)— %an%C(reset)%C(bold yellow)%d%C(reset)' --abbrev-commit --date=relative"
alias gf="git fetch"
