#!/usr/bin/sh
# river/init
# @author nate zhou
# @since 2025,2026

# 启用 xwayland (Steam 等 X11 应用需要)
riverctl xwayland
export DISPLAY=:0

# https://codeberg.org/unixchad/kwm
# https://github.com/gnuunixchad/kwm
/usr/local/bin/kwm &
