#!/usr/bin/sh
# @author nate zhou
# @since 2025,2026
# qute-dict - search the word currently selected in qutebrowser with dictd
# @depends dictd (and a dictionary database) foot st(xorg)

# usage:
# config.bind('xd', 'spawn --userscript qutedict')

# > [!Note]
# > 1. `dict` outputs to STDERR when there's no exact matched word, which can
#       be useful(`2>&1` also avoids a confusing empty terminial).
# > 2. Avoid piping dict's output to less directly which results in a fronzen
# >    terminial, which is not scrollable nor searchable.

DICT_TEMP=${XDG_RUNTIME_DIR}/qutebrowser/qutedict

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    FLOAT_TERM="footclient -T Floating_Term \
                     -o main.font=NotoSansMNFM:size=20 \
                     -o colors.alpha=0.9"
elif [ -n "$XAUTHORITY" ]; then
    FLOAT_TERM="st -T Floating_Term -f NotoSansMNFM:size=20"
fi

/usr/bin/dict "$QUTE_SELECTED_TEXT" > "$DICT_TEMP" 2>&1

eval $FLOAT_TERM /usr/bin/less "$DICT_TEMP"
